#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: block-nginx
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: block-nginx
#  template:
#    metadata:
#      labels:
#        app: block-nginx
#    spec:
#      containers:
#      - name: block-nginx
#        image: k8s.gcr.io/nginx-slim:0.8
#        ports:
#        - containerPort: 80
#        volumeMounts:
#        - name: csi-pod-pvc-1
#          mountPath: /csi-1
#        - name: csi-pod-pvc-2
#          mountPath: /csi-2
#      volumes:
#      - name: csi-pod-pvc-1
#        persistentVolumeClaim:
#          claimName: csi-pod-pvc-1
#      - name: csi-pod-pvc-2
#        persistentVolumeClaim:
#          claimName: csi-pod-pvc-2
#---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pod-pvc-2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pod-pvc-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
